# workflow name
name: "Sanity Checks"

# fire on
on: [push, pull_request]

#########
# actions
#########
# actions/checkout@v3.3.0
# actions/setup-python@v4.5.0
# miketrethewey/ootmm_pack_mm1/test

jobs:
  # Test
  test:
    name: 🧮
    runs-on: ${{ matrix.os-name }}

    strategy:
      matrix:
        os-name: [
          ubuntu-latest
        ]
        python-version: [
          "3.10"
        ]

    steps:
      # checkout commit
      - name: ✔️Checkout commit
        uses: actions/checkout@v3.3.0
      # install python
      - name: 💿Install Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      # python version
      - name: 🐍Python Version
        shell: bash
        run: |
          python --version
      # python modules
      - name: 🐍Python Modules
        shell: bash
        run: |
          python -m pip install -r "./resources/app/manifests/pip_requirements.txt"
      # test
      - name: ⏱️Call Test
        uses: ./.github/actions/test
